# Generated by Django 2.2.16 on 2020-10-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201025_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jmj',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='khj',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
